export const diningCopy = {
  EN: {
    interiorConcept: 'Interior concept', interiorDisclaimer: 'Illustrative interior, not an exact table view.',
    pauseMotion: 'Pause interior motion', playMotion: 'Play interior motion',
    heroStageRestaurant: 'Choose the atmosphere.', heroStagePlan: 'Read the whole room.', heroStageTable: 'See the seat before you arrive.',
    saveRestaurant: 'Save restaurant', removeSaved: 'Remove from saved', savedOnly: 'Saved',
    savedHere: 'Your shortlist, saved on this device.', storageFallback: 'Saved for this visit. Browser storage is unavailable.',
    seatPreference: 'Your kind of seat', anySeat: 'Surprise me', suggestSeat: 'Find my seat',
    matchNote: 'A good fit for your group and preference.', noMatch: 'No matching table at this time. Try another preference or time.',
    noAvailable: 'No tables for this group and time. Try another time or a smaller group.',
    calendarDownloaded: 'Calendar file downloaded. Open it to add your plan.', sharedCopied: 'Plan link copied — ready to send.',
    shareFallback: 'Copy this link to share your plan.', demoPlan: 'Demo only. No reservation has been sent to the restaurant.',
    backToTable: 'See your table', planSaved: 'Your dining plan', planReady: 'Your evening, planned.',
    chooseSeat: 'Choose your exact seat', seatLabel: 'Seat', seatSelected: 'Your selected place',
    viewFromSeat: 'Sit here and see the view', dragToLook: 'Drag left or right to look around',
    turnLeft: 'Turn the view left', turnRight: 'Turn the view right', viewAngle: 'View angle',
    capacityLabel: 'Capacity', shapeLabel: 'Table shape', roundTable: 'Round', squareTable: 'Square', longTable: 'Long',
    tableCategories: 'Best for', roomOverview: 'Room', tableOverview: 'Table', guestView: 'Your seat',
  },
  AZ: {
    interiorConcept: 'İnteryer konsepti', interiorDisclaimer: 'Nümunə interyer — masadan dəqiq görünüş deyil.',
    pauseMotion: 'İnteryer hərəkətini dayandır', playMotion: 'İnteryer hərəkətini başlat',
    heroStageRestaurant: 'Atmosferi seçin.', heroStagePlan: 'Bütün zalı görün.', heroStageTable: 'Gəlməzdən əvvəl yerinizi görün.',
    saveRestaurant: 'Restoranı yadda saxla', removeSaved: 'Yadda saxlanmışlardan sil', savedOnly: 'Seçilmişlər',
    savedHere: 'Seçimləriniz bu cihazda saxlanılır.', storageFallback: 'Bu ziyarət üçün saxlanıldı. Brauzer yaddaşı əlçatan deyil.',
    seatPreference: 'Sizə uyğun yer', anySeat: 'Fərqi yoxdur', suggestSeat: 'Mənə masa tap',
    matchNote: 'Qrupunuza və seçiminizə uyğun masa.', noMatch: 'Bu saat üçün uyğun masa yoxdur. Başqa seçim və ya saat sınayın.',
    noAvailable: 'Bu qrup və saat üçün masa yoxdur. Başqa saat və ya daha az qonaq seçin.',
    calendarDownloaded: 'Təqvim faylı endirildi. Planınızı əlavə etmək üçün açın.', sharedCopied: 'Planın keçidi kopyalandı.',
    shareFallback: 'Planı paylaşmaq üçün keçidi kopyalayın.', demoPlan: 'Yalnız demo. Restorana rezervasiya göndərilməyib.',
    backToTable: 'Masanıza baxın', planSaved: 'Yemək planınız', planReady: 'Gözəl bir plan hazırdır.',
    chooseSeat: 'Dəqiq yerinizi seçin', seatLabel: 'Yer', seatSelected: 'Seçdiyiniz yer',
    viewFromSeat: 'Əyləşin və mənzərəni görün', dragToLook: 'Ətrafa baxmaq üçün sağa və ya sola sürüşdürün',
    turnLeft: 'Görünüşü sola çevir', turnRight: 'Görünüşü sağa çevir', viewAngle: 'Baxış bucağı',
    capacityLabel: 'Tutum', shapeLabel: 'Masanın forması', roundTable: 'Dairəvi', squareTable: 'Kvadrat', longTable: 'Uzun',
    tableCategories: 'Uyğundur', roomOverview: 'Zal', tableOverview: 'Masa', guestView: 'Yeriniz',
  },
  RU: {
    interiorConcept: 'Концепция интерьера', interiorDisclaimer: 'Иллюстрация интерьера, не точный вид со столика.',
    pauseMotion: 'Остановить движение', playMotion: 'Включить движение',
    heroStageRestaurant: 'Выберите атмосферу.', heroStagePlan: 'Увидьте весь зал.', heroStageTable: 'Посмотрите место до визита.',
    saveRestaurant: 'Сохранить ресторан', removeSaved: 'Убрать из избранного', savedOnly: 'Избранное',
    savedHere: 'Избранное хранится на этом устройстве.', storageFallback: 'Сохранено на время визита. Хранилище браузера недоступно.',
    seatPreference: 'Ваше любимое место', anySeat: 'На ваш выбор', suggestSeat: 'Подобрать столик',
    matchNote: 'Подходит вашей компании и пожеланиям.', noMatch: 'Подходящих столиков нет. Измените пожелание или время.',
    noAvailable: 'Нет столиков для этой компании и времени. Выберите другое время или меньше гостей.',
    calendarDownloaded: 'Файл календаря скачан. Откройте его, чтобы добавить план.', sharedCopied: 'Ссылка на план скопирована.',
    shareFallback: 'Скопируйте ссылку, чтобы поделиться планом.', demoPlan: 'Только демо. Бронь не отправлена в ресторан.',
    backToTable: 'Ваш столик', planSaved: 'Ваш план ужина', planReady: 'Прекрасный план готов.',
    chooseSeat: 'Выберите точное место', seatLabel: 'Место', seatSelected: 'Выбранное место',
    viewFromSeat: 'Сесть и увидеть вид', dragToLook: 'Проведите влево или вправо, чтобы осмотреться',
    turnLeft: 'Повернуть вид влево', turnRight: 'Повернуть вид вправо', viewAngle: 'Угол обзора',
    capacityLabel: 'Вместимость', shapeLabel: 'Форма стола', roundTable: 'Круглый', squareTable: 'Квадратный', longTable: 'Длинный',
    tableCategories: 'Лучше всего', roomOverview: 'Зал', tableOverview: 'Стол', guestView: 'Ваше место',
  },
} as const;
