export const diningCopy = {
  EN: {
    pauseMotion: 'Pause interior motion', playMotion: 'Play interior motion',
    heroStageRestaurant: 'Choose the atmosphere.', heroStagePlan: 'Read the whole room.', heroStageTable: 'Choose the table that feels right.',
    saveRestaurant: 'Save restaurant', removeSaved: 'Remove from saved', savedOnly: 'Saved',
    savedHere: 'Your shortlist, saved on this device.', storageFallback: 'Saved for this visit. Browser storage is unavailable.',
    seatPreference: 'Your preferred table', anySeat: 'Surprise me', suggestSeat: 'Suggest a table',
    matchNote: 'A good fit for your group and preference.', noMatch: 'No matching table at this time. Try another preference or time.',
    noAvailable: 'No tables for this group and time. Try another time or a smaller group.',
    calendarDownloaded: 'Calendar file downloaded. Open it to add your plan.', sharedCopied: 'Plan link copied — ready to send.',
    shareFallback: 'Copy this link to share your plan.', demoPlan: 'Demo only. No reservation has been sent to the restaurant.',
    planSaved: 'Your dining plan', planReady: 'Your evening, planned.',
    chooseSeat: 'Review your table', seatLabel: 'Seat', seatSelected: 'Your selected place',
    reserveSeat: 'Reserve this table', openStage: 'Open',
    capacityLabel: 'Capacity', shapeLabel: 'Table shape', roundTable: 'Round', squareTable: 'Square', longTable: 'Long',
    tableCategories: 'Best for', roomOverview: 'Room & table', tableAndSeat: 'Selected table',
    yourSelectedTable: 'Your selected table', tableSelected: 'Table selected', reserveTable: 'Reserve this table', tableOnlyNote: 'Table selection only · individual seats are assigned by the restaurant',
    account: 'Account', signIn: 'Sign in', createAccount: 'Create account', signInTitle: 'Welcome back', createAccountTitle: 'Create your OTUR account',
    accountDescription: 'Sign in to reserve, view and cancel your tables.', password: 'Password', passwordHelp: 'Use at least 8 characters.', pleaseWait: 'One moment…',
    signInError: 'Email or password is not correct on this device.', accountError: 'Enter a name, valid email, +994 phone and an 8+ character password.', accountExists: 'An account with this email already exists on this device.',
    useDemoAccount: 'Continue as demo guest', demoAccountNote: 'Explore the full booking flow instantly.', demoGuest: 'Demo Guest', or: 'or',
    localAccountNote: 'Prototype account only. Details stay in this browser and are not sent to a server.', myOtur: 'My OTUR', yourTables: 'Your tables', noReservations: 'No reservations yet. Choose a table to start.',
    confirmed: 'Confirmed', cancelled: 'Cancelled', cancelReservation: 'Cancel reservation', cancelQuestion: 'Cancel this reservation?', keepReservation: 'Keep it', yesCancel: 'Yes, cancel', contactToCancel: 'Contact restaurant to cancel',
    cancellationPolicy: 'Free cancellation until 2 hours before your reservation. Later changes require contacting the restaurant.', signOut: 'Sign out', profile: 'Profile', reservationsNav: 'Reservations',
    localReservationNote: 'Prototype reservation saved to this account on this device. No restaurant has been contacted.', acceptCancellationPolicy: 'I understand the cancellation policy.',
    details: 'Restaurant details', beforeYouGo: 'Everything before you go', address: 'Address', contact: 'Contact', hoursOfOperation: 'Hours of operation', paymentOptions: 'Payment options', parking: 'Parking', dressCode: 'Dress code', executiveChef: 'Executive chef', accessibility: 'Accessibility', openInMaps: 'Open in Maps',
    venuePrototypeNote: 'Venue names, addresses and availability are simulated for this product prototype.',
    reserveDescription: 'Review the table and contact details connected to your account.', backToTable: 'Back to table',
  },
  AZ: {
    pauseMotion: 'İnteryer hərəkətini dayandır', playMotion: 'İnteryer hərəkətini başlat',
    heroStageRestaurant: 'Atmosferi seçin.', heroStagePlan: 'Bütün zalı görün.', heroStageTable: 'Sizə uyğun masanı seçin.',
    saveRestaurant: 'Restoranı yadda saxla', removeSaved: 'Yadda saxlanmışlardan sil', savedOnly: 'Seçilmişlər',
    savedHere: 'Seçimləriniz bu cihazda saxlanılır.', storageFallback: 'Bu ziyarət üçün saxlanıldı. Brauzer yaddaşı əlçatan deyil.',
    seatPreference: 'Masa seçiminiz', anySeat: 'Fərqi yoxdur', suggestSeat: 'Masa təklif et',
    matchNote: 'Qrupunuza və seçiminizə uyğun masa.', noMatch: 'Bu saat üçün uyğun masa yoxdur. Başqa seçim və ya saat sınayın.',
    noAvailable: 'Bu qrup və saat üçün masa yoxdur. Başqa saat və ya daha az qonaq seçin.',
    calendarDownloaded: 'Təqvim faylı endirildi. Planınızı əlavə etmək üçün açın.', sharedCopied: 'Planın keçidi kopyalandı.',
    shareFallback: 'Planı paylaşmaq üçün keçidi kopyalayın.', demoPlan: 'Yalnız demo. Restorana rezervasiya göndərilməyib.',
    planSaved: 'Yemək planınız', planReady: 'Gözəl bir plan hazırdır.',
    chooseSeat: 'Dəqiq yerinizi seçin', seatLabel: 'Yer', seatSelected: 'Seçdiyiniz yer',
    reserveSeat: 'Bu yeri rezerv et', openStage: 'Aç',
    capacityLabel: 'Tutum', shapeLabel: 'Masanın forması', roundTable: 'Dairəvi', squareTable: 'Kvadrat', longTable: 'Uzun',
    tableCategories: 'Uyğundur', roomOverview: 'Zal və masa', tableAndSeat: 'Seçilmiş masa',
    yourSelectedTable: 'Seçdiyiniz masa', tableSelected: 'Masa seçildi', reserveTable: 'Bu masanı rezerv et', tableOnlyNote: 'Yalnız masa seçimi · konkret yerləri restoran təyin edir',
    account: 'Hesab', signIn: 'Daxil ol', createAccount: 'Hesab yarat', signInTitle: 'Yenidən xoş gəldiniz', createAccountTitle: 'OTUR hesabınızı yaradın',
    accountDescription: 'Masa rezerv etmək, baxmaq və ləğv etmək üçün daxil olun.', password: 'Şifrə', passwordHelp: 'Ən azı 8 simvol istifadə edin.', pleaseWait: 'Bir an…',
    signInError: 'Bu cihazda e-poçt və ya şifrə düzgün deyil.', accountError: 'Ad, düzgün e-poçt, +994 telefon və ən azı 8 simvolluq şifrə daxil edin.', accountExists: 'Bu e-poçtla hesab artıq bu cihazda mövcuddur.',
    useDemoAccount: 'Demo qonaq kimi davam et', demoAccountNote: 'Rezervasiya axınını dərhal sına.', demoGuest: 'Demo Qonaq', or: 'və ya',
    localAccountNote: 'Yalnız prototip hesabıdır. Məlumatlar bu brauzerdə qalır və serverə göndərilmir.', myOtur: 'Mənim OTUR', yourTables: 'Masalarınız', noReservations: 'Hələ rezervasiyanız yoxdur. Başlamaq üçün masa seçin.',
    confirmed: 'Təsdiqlənib', cancelled: 'Ləğv edilib', cancelReservation: 'Rezervasiyanı ləğv et', cancelQuestion: 'Bu rezervasiya ləğv edilsin?', keepReservation: 'Saxla', yesCancel: 'Bəli, ləğv et', contactToCancel: 'Ləğv üçün restoranla əlaqə saxlayın',
    cancellationPolicy: 'Rezervasiyadan 2 saat əvvələ qədər pulsuz ləğv. Daha gec dəyişiklik üçün restoranla əlaqə saxlayın.', signOut: 'Çıxış', profile: 'Profil', reservationsNav: 'Rezervasiyalar',
    localReservationNote: 'Prototip rezervasiya bu cihazdakı hesabda saxlanılır. Restorana məlumat göndərilməyib.', acceptCancellationPolicy: 'Ləğv qaydalarını anlayıram.',
    details: 'Restoran məlumatları', beforeYouGo: 'Getməzdən əvvəl hər şey', address: 'Ünvan', contact: 'Əlaqə', hoursOfOperation: 'İş saatları', paymentOptions: 'Ödəniş üsulları', parking: 'Dayanacaq', dressCode: 'Geyim qaydası', executiveChef: 'Baş aşpaz', accessibility: 'Əlçatanlıq', openInMaps: 'Xəritədə aç',
    venuePrototypeNote: 'Məkan adları, ünvanlar və mövcudluq bu məhsul prototipi üçün simulyasiya edilib.',
    reserveDescription: 'Masanı və hesabınızdakı əlaqə məlumatlarını yoxlayın.', backToTable: 'Masaya qayıt',
  },
  RU: {
    pauseMotion: 'Остановить движение', playMotion: 'Включить движение',
    heroStageRestaurant: 'Выберите атмосферу.', heroStagePlan: 'Увидьте весь зал.', heroStageTable: 'Выберите подходящий стол.',
    saveRestaurant: 'Сохранить ресторан', removeSaved: 'Убрать из избранного', savedOnly: 'Избранное',
    savedHere: 'Избранное хранится на этом устройстве.', storageFallback: 'Сохранено на время визита. Хранилище браузера недоступно.',
    seatPreference: 'Предпочтения по столу', anySeat: 'На ваш выбор', suggestSeat: 'Предложить стол',
    matchNote: 'Подходит вашей компании и пожеланиям.', noMatch: 'Подходящих столиков нет. Измените пожелание или время.',
    noAvailable: 'Нет столиков для этой компании и времени. Выберите другое время или меньше гостей.',
    calendarDownloaded: 'Файл календаря скачан. Откройте его, чтобы добавить план.', sharedCopied: 'Ссылка на план скопирована.',
    shareFallback: 'Скопируйте ссылку, чтобы поделиться планом.', demoPlan: 'Только демо. Бронь не отправлена в ресторан.',
    planSaved: 'Ваш план ужина', planReady: 'Прекрасный план готов.',
    chooseSeat: 'Выберите точное место', seatLabel: 'Место', seatSelected: 'Выбранное место',
    reserveSeat: 'Забронировать это место', openStage: 'Открыть',
    capacityLabel: 'Вместимость', shapeLabel: 'Форма стола', roundTable: 'Круглый', squareTable: 'Квадратный', longTable: 'Длинный',
    tableCategories: 'Лучше всего', roomOverview: 'Зал и стол', tableAndSeat: 'Выбранный стол',
    yourSelectedTable: 'Ваш выбранный стол', tableSelected: 'Стол выбран', reserveTable: 'Забронировать этот стол', tableOnlyNote: 'Выбор только стола · конкретные места назначает ресторан',
    account: 'Аккаунт', signIn: 'Войти', createAccount: 'Создать аккаунт', signInTitle: 'С возвращением', createAccountTitle: 'Создайте аккаунт OTUR',
    accountDescription: 'Войдите, чтобы бронировать, просматривать и отменять столы.', password: 'Пароль', passwordHelp: 'Не менее 8 символов.', pleaseWait: 'Один момент…',
    signInError: 'Неверный email или пароль на этом устройстве.', accountError: 'Введите имя, корректный email, телефон +994 и пароль от 8 символов.', accountExists: 'Аккаунт с таким email уже есть на этом устройстве.',
    useDemoAccount: 'Продолжить как демо-гость', demoAccountNote: 'Сразу попробуйте весь процесс бронирования.', demoGuest: 'Демо-гость', or: 'или',
    localAccountNote: 'Это прототип аккаунта. Данные остаются в браузере и не отправляются на сервер.', myOtur: 'Мой OTUR', yourTables: 'Ваши столы', noReservations: 'Бронирований пока нет. Выберите стол, чтобы начать.',
    confirmed: 'Подтверждено', cancelled: 'Отменено', cancelReservation: 'Отменить бронь', cancelQuestion: 'Отменить эту бронь?', keepReservation: 'Оставить', yesCancel: 'Да, отменить', contactToCancel: 'Свяжитесь с рестораном',
    cancellationPolicy: 'Бесплатная отмена не позднее чем за 2 часа. Позже свяжитесь с рестораном.', signOut: 'Выйти', profile: 'Профиль', reservationsNav: 'Брони',
    localReservationNote: 'Бронь-прототип сохранена в аккаунте на этом устройстве. Ресторан не получил заявку.', acceptCancellationPolicy: 'Я понимаю правила отмены.',
    details: 'О ресторане', beforeYouGo: 'Всё перед визитом', address: 'Адрес', contact: 'Контакты', hoursOfOperation: 'Часы работы', paymentOptions: 'Оплата', parking: 'Парковка', dressCode: 'Дресс-код', executiveChef: 'Шеф-повар', accessibility: 'Доступность', openInMaps: 'Открыть карту',
    venuePrototypeNote: 'Названия, адреса и доступность заведений смоделированы для прототипа продукта.',
    reserveDescription: 'Проверьте стол и контактные данные из аккаунта.', backToTable: 'Вернуться к столу',
  },
} as const;
